typography_spectrum: 0.47157
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#373d39'
    - '#b4c4aa'
    - '#8a9382'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.24819
analytics:
  google: null
  facebook: null
  twitter: null
name: Christopher Weddle
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Christopher Weddle
description: Actor
purpose: []
